### ISSUE TITLE
What do I enter as username and password?

### ISSUE THREAD

**Issue by hjs3372** [djerik/beolink-ha#1]
What do I enter as username and password?
I already have one BLGW hardware.
I see my new BeoLink Bridge name in the Beolink2 app.
So when I try to add, I have to enter the user and password and press the login button.
I don't know what to enter.

**Comment by djerik** [comment]
You login with your HA username and password.

You don't need to have a BLGW/BLI.

Install guide:
1) install the BeoLink component in HA, add entities to rooms
2) start the BeoLiving app.
3) Add the new HA emulated BLGW manual if it does not find it by itself.
4) login in the app with your HA credentials

I would love to get some feedback on this component

**Comment by hjs3372** [comment]
Your project is very interesting. It's great.
Hope it works for me as well.

I installed it as per your instructions, but I'm having trouble logging in.
I tried logging in with HA's account, but it stayed at "Authorizing" for a long time and eventually failed.
I am also posting some screenshots of my settings.
The last photo is the log that appears to be problematic.

I'll delete the picture later.

![스크린샷 2023-11-25 오후 4 32 35](https://github.com/djerik/beolink-ha/assets/75467134/9b1ffecc-1e56-4e73-bc67-5c813c71db17)
![스크린샷 2023-11-25 오후 4 34 59](https://github.com/djerik/beolink-ha/assets/75467134/9e1a0f93-4042-4615-b148-809d92de24eb)
![스크린샷 2023-11-25 오후 4 37 53](https://github.com/djerik/beolink-ha/assets/75467134/1ae85969-b6b5-4e57-9ea7-81f6fbb582bd)
![스크린샷 2023-11-25 오후 4 38 48](https://github.com/djerik/beolink-ha/assets/75467134/15a604e3-488c-4fc5-9b04-955d8bfe74a4)

**Comment by djerik** [comment]
Thank you the screenshots. I see that you are using the trusted network authentication provider. This is not yet supported but I will try to implement it this weekend

**Comment by djerik** [comment]
I have added support for trusted network auth. Please update to the latest version
